spring:
  profiles:
    active: prod
    group:
      development:
        - local
      production:
        - prod

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: h2

logging:
  level:
    org.hibernate.sql: debug

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
#    url: jdbc:${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASSSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ccqsjzfamhdgcw:8260a9e63e07b4f965db208d88cf963122f174f382b70ac23b291d06ece6fc47@ec2-44-205-64-253.compute-1.amazonaws.com:5432/df27kj78eckbbi
    username: ccqsjzfamhdgcw
    password: 8260a9e63e07b4f965db208d88cf963122f174f382b70ac23b291d06ece6fc47

  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql

logging:
  level:
    org.hibernate.sql: debug