spring:
  profiles:
    active: local
    group:
      development:
        - local
      production:
        - prod
        -
---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSSWORD}
    driver-class-name:

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug