name: deploy

#github에 push를 하면 작동한다.
on:
  push:
    branches: [ "main" ]

#이 액션은 아래의 일을 합니다.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #내 github repo를 가지고 온다.
      - name: checkout backend
        uses: actions/checkout@v2
      #해당 pc에 자바를 설치하고
      - name: Setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      #헤로쿠에 배포한다.
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cloudwi"
          heroku_email: "cloudwi@naver.com"

